# Snakefile for Illumina Trusight Cancer workflow

configfile: "config.json"
include: "/data/DefaultPipelines/rules/references/human.rules"
include: "/data/DefaultPipelines/rules/references/illumina.rules"
include: "/data/DefaultPipelines/rules/trim/trimmomatic.rules"
include: "/data/DefaultPipelines/rules/mapping/bwa_mem_pe.rules"
include: "/data/DefaultPipelines/rules/mapping/samfiles.rules"
include: "/data/DefaultPipelines/rules/mapping/picard.rules"
include: "/data/DefaultPipelines/rules/coverage/bed_coverage.rules"
include: "/data/DefaultPipelines/rules/coverage/plots.rules"
include: "/data/DefaultPipelines/rules/coverage/CNV.rules"
include: "/data/DefaultPipelines/rules/variant/gatk.rules"
include: "/data/DefaultPipelines/rules/qa/fastqc.rules"
include: "/data/DefaultPipelines/rules/de/feature_count.rules"

rule all:
	input:
		"plots/coverage/illumina/hg19/adapter_trimmed/BRCA1-ENST00000357654.pdf"
		,"plots/CNV/illumina/hg19/adapter_trimmed/BRCA1-ENST00000357654.pdf"
		,"plots/coverage/illumina/hg19/adapter_trimmed/Total.pdf"
		,expand("results/CNV/illumina/hg19/adapter_trimmed/{patient}_CNV.txt", patient = config["samples"].keys() )
		,expand("results/coverage/illumina/hg19/adapter_trimmed/{patient}_20_20.lower100", patient = config["samples"].keys() )
		,expand("results/coverage/illumina/hg19/adapter_trimmed/{patient}_20_20.lower60", patient = config["samples"].keys() )
		,expand("results/coverage/illumina/hg19/adapter_trimmed/{patient}_20_20.lower30", patient = config["samples"].keys() )
		,expand("results/coverage/illumina/hg19/adapter_trimmed/{patient}_20_20.lower10", patient = config["samples"].keys() )
		,expand("results/qa/fastqc/adapter_trimmed/{unit}_fastqc.html", unit = [w.replace('.fastq.gz', '') for w in sum(config["units"].values(), [])] )
		,"results/variants/gatk/hg19/adapter_trimmed/" + config["run"] + "_rs_SNPs.tsv"
