#############################################################################
#          Script of the standard trusight cancer pipeline.                 #
#                                                                           #
# Date: 02.01.2015                                                          #
#                                                                           #
# Example usage: snakemake --snakefile project.snake                        #
#############################################################################

configfile: "config.json"
include: "/data/DefaultPipelines/rules/references/human.rules"
include: "/data/DefaultPipelines/rules/references/illumina.rules"
include: "/data/DefaultPipelines/rules/trim/trimmomatic_pe.rules"
include: "/data/DefaultPipelines/rules/mapping/bwa_mem_pe.rules"
include: "/data/DefaultPipelines/rules/mapping/samfiles.rules"
include: "/data/DefaultPipelines/rules/mapping/picard.rules"
include: "/data/DefaultPipelines/rules/coverage/bed_coverage.rules"
include: "/data/DefaultPipelines/rules/coverage/plots.rules"
include: "/data/DefaultPipelines/rules/variant/gatk.rules"
include: "/data/DefaultPipelines/rules/qa/fastqc.rules"
include: "/data/DefaultPipelines/rules/de/feature_count.rules"

rule all:
    input: expand("results/qa/fastqc/raw/{unit}_fastqc.html", unit = [w.replace('.fastq.gz', '') for w in sum(config["units"].values(), [])] )
