#############################################################################
#          Script of the standard trusight cancer pipeline.                 #
#                                                                           #
# Date: 02.01.2015                                                          #
#                                                                           #
# Example usage: snakemake --snakefile project.snake                        #
#############################################################################

configfile: "config.json"

include: "/data/references/references.rules"

include: "/home/bull/DefaultPipelines/ngs/rules/mapping/bwa_mem.rules"

include: "/home/bull/DefaultPipelines/ngs/rules/mapping/samfiles.rules"

include: "/home/bull/DefaultPipelines/ngs/rules/variant/gatk.rules"

rule all:
    input: expand( "results/mapping/hg38/raw/{unit}_dedup.bam", unit = config["units"].keys() ),
           expand( "results/coverage/raw/{unit}/illumina_trusight_cancer.bed", unit = config["units"].keys() )
